apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-app
  labels:
    app: spring-code

spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-code
  
  template:
    metadata:
      name: spring-app
      labels:
        app: spring-code


    spec:
      containers:
      - name : spring-app
        image : sudo1amir/springcode:v1
