apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-app
  namespace: jenkins
  labels:
    app: spring-code

spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-code
  
  template:
    metadata:
      labels:
        app: spring-code


    spec:
      containers:
      - name : spring-app
        image : nginx
        ports:
        - name: app-port
          containerPort: 80