apiVersion: v1
kind: Service
metadata:
  name: my-service
  namespace: jenkins
spec:
  type: NodePort
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30020
  selector:
        app: spring-code
